import diophantine_approximation_probabilistic_number_theory_lemma_canonical_lane_mathlib.GateLemmas
import diophantine_approximation_probabilistic_number_theory_lemma_canonical_lane_mathlib.FinalTheorem
